// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp_Traffic.Data;

#nullable disable

namespace WebApp_Traffic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221208214252_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApp_Traffic.Models.Traffic", b =>
                {
                    b.Property<int>("Id_Traffic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Traffic"), 1L, 1);

                    b.Property<DateTime>("EntryOrOut_Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type_Traffic")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id_Traffic");

                    b.HasIndex("userId");

                    b.ToTable("Traffics");
                });

            modelBuilder.Entity("WebApp_Traffic.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("National_Code")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApp_Traffic.Models.Traffic", b =>
                {
                    b.HasOne("WebApp_Traffic.Models.User", "user")
                        .WithMany("Traffics")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("WebApp_Traffic.Models.User", b =>
                {
                    b.Navigation("Traffics");
                });
#pragma warning restore 612, 618
        }
    }
}
